repos:
    - hooks:
      - {id: seed-isort-config, language_version: python3.9}
      repo: https://github.com/asottile/seed-isort-config
      rev: v2.2.0
    - hooks:
      - {id: isort, language_version: python3.9}
      repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.6.4
    - hooks:
      - {id: black, args: ['-l', '79'], language_version: python3.9}
      repo: https://github.com/ambv/black
      rev: 20.8b1
    - hooks:
      - {id: trailing-whitespace, language_version: python3.9}
      - {id: end-of-file-fixer, language_version: python3.9}
      - {id: debug-statements, language_version: python3.9, exclude: ^wdb_server/main/views.py}
      - {id: check-merge-conflict, language_version: python3.9}
      - {id: mixed-line-ending, language_version: python3.9}
      - {id: requirements-txt-fixer, language_version: python3.9}
      repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.3.0
    - hooks:
      - {id: flake8, additional_dependencies: [flake8-bugbear == 18.8.0], language_version: python3.9}
      repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.4
    # - hooks:
    #   - {id: flake8, name: flake8, description: wemake-python-styleguide enforcement, entry: flake8, args: ["--config=.flake8"], language: python, types: [python]}
    #   repo: local
    - hooks:
      - {id: pyupgrade, language_version: python3.9}
      repo: https://github.com/asottile/pyupgrade
      rev: v2.7.3
    - hooks:
      - {id: python-safety-dependencies-check, args: ['requirements/production.txt'], language_version: python3.9}
      repo: https://github.com/Lucas-C/pre-commit-hooks-safety
      rev: v1.1.3
    # - hooks:
    #   - id: commitlint
    #     stages: [commit-msg]
    #   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    #   rev: 2.0.0
    - hooks:
      - additional_dependencies: []
        entry: pylint
        exclude: "(?x)^(\n    config/.*|\n    docs/.*|\n    requirements/.*\n|\n    .*/tests/.*|\n    .*/migrations/.*|\n)$"
        id: pylint
        language_version: python3.9
      repo: https://github.com/pre-commit/mirrors-pylint.git
      rev: v2.6.0
    - hooks:
      - id: mypy
        files: ^wdb_server/
        language_version: python3.9
        exclude: "(?x)^(\n    .*/tests/.*|\n    .*/migrations/.*|\n)$"
      repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.790
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v2.1.2"
      hooks:
        - id: prettier
          files: \.(ts|js|scss)$
